###Route for Viewing all Course
GET http://localhost:5000/student-api/courses

###Course Payment
POST http://localhost:5000/student-api/pay
Content-Type: application/json

{
    "student":"6a1139368c625762b63a88fb",
    "course":"6a11384f8c625762b63a88f9",
    "amount":100,
    "method":"CARD",
    "status":"SUCCESS",
    "transactionId":"e41ce21b783f7027a695cb2136dc9bfe7b78fd38f9a537c30911fb4897bc7d25"
}

###Course Enrollment
POST http://localhost:5000/student-api/enroll
Content-Type: application/json

{
    "student":"6a1139368c625762b63a88fb",
    "course":"6a11384f8c625762b63a88f9",
    "payment":"6a1139c08c625762b63a88fc"
}

###Route for viewing Student Enrolled Courses
GET http://localhost:5000/student-api/course
Content-Type: application/json

###Route for Dropping a Course which Student has enrolled in
PATCH http://localhost:5000/student-api/course
Content-Type: application/json

{
    "courseId":"6a11384f8c625762b63a88f9",
    "status":"Dropped"
}

###Route for Adding Comments to a Course
PUT http://localhost:5000/student-api/course
Content-Type: application/json

{
    "courseId":"6a11384f8c625762b63a88f9",
    "rating":5,
    "comment":"This Course is Very Instructive"
}